server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaokunxiong/project1	#先 在github上创建一个对应的project
          username: 
          password: 
  application:
    name: chinasofti-sp-config	# 配置文件就是用这个来做文件名的

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password456@localhost:8761/eureka
  instance:
    prefer-ip-address: true